spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: experiment
    password: experiment
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
      id:
        new_generator_mappings: true
        optimizer.pooled.preferred: pooled-lo
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml

experiment:
  total-records: 100000
  simulation-type: sequence
  change-probability: 0.4