spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: experiment
    password: experiment
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        jdbc.batch_size: ${sequence.batch-size}
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml

sequence:
  total-records: 100000
  batch-size: 1000

historic:
  total-records: 100000
  batch-size: 1000
  change-probability: 0.4

mtm:
  batch-size: 1000
  days: 10
  change-probability: 0.01