spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: experiment
    password: experiment
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
      id:
        new_generator_mappings: true
        optimizer.pooled.preferred: pooled-lo
      properties:
        hibernate.jdbc.batch_size: ${experiment.batch-size}
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.jdbc.batch_versioned_data: true
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml

experiment:
  total-records: 100000
  batch-size: 1000
  change-probability: 0.4

mtm:
  batch-size: 1000
  days: 10
  change-probability: 0.01